apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-crm.fullname" . }}
  labels:
    {{- include "helm-crm.labels" . | nindent 4 }}    
    
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-crm.selectorLabels" . | nindent 6 }}
  template:
    metadata:      
      annotations:              
        rollme: {{ randAlphaNum 5 | quote }}        
      labels:        
        {{- include "helm-crm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:      
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:    
        options:
          - name: ndots
            value: "1"
        nameservers:
          - 10.43.0.10  # Kubernetes DNS (verify this is correct for your cluster)
          - 8.8.8.8
          - 1.1.1.1
        searches:
          - deployaja.svc.cluster.local
          - svc.cluster.local
          - cluster.local
          - techarea.co.id
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}        
      serviceAccountName: {{ include "helm-crm.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.configMap.enabled }}
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_LOGS_INJECTION
              value: "true"
          envFrom:
            - secretRef:
                name: {{ include "helm-crm.fullname" . }}
            - configMapRef:
                name: {{ include "helm-crm.fullname" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
            {{- if .Values.wwebjs.enabled }}
            - name: wwebjs-auth
              mountPath: /usr/src/app/.wwebjs_auth
            {{- end }}
      volumes:
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        {{- if .Values.wwebjs.enabled }}
        - name: wwebjs-auth
          persistentVolumeClaim:
            claimName: {{ include "helm-crm.fullname" . }}-wwebjs-auth
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
