{{- if .Values.ingress.enabled }}
ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: true
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: {{ .Values.ingress.host | default "pinuspintar.id" }}
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "helm-crm.fullname" . }}
              port:
                number: {{ .Values.service.port | default 8070 }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | default "pinuspintar.id" }}
    secretName: {{ .Values.ingress.host | default "pinuspintar.id" }}-tls
{{- end }}