{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-crm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    {{- include "helm-crm.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "traefik" }}
  rules:
    - host: {{ .Values.ingress.host | default "pinuspintar.id" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm-crm.fullname" . }}
                port:
                  number: {{ .Values.service.port | default 8070 }}
  {{- if .Values.deployaja.enabled }}
  tls:
  - hosts:
    - '*.deployaja.id'
    secretName: deployaja-tls-secret
  {{- else }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | default "pinuspintar.id" }}
    secretName: {{ .Values.ingress.host | default "pinuspintar.id" }}-tls
  {{- end }}
{{- end }}