{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-crm.fullname" . }}-init
  labels:
    {{- include "helm-crm.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: init
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
        imagePullPolicy: {{ .Values.job.image.pullPolicy | default "IfNotPresent" }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            npm run prisma:migrate
            npm run prisma:seed
        env:
          {{- with .Values.job.env }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        resources:
          {{- toYaml .Values.job.resources | nindent 10 }}
      restartPolicy: OnFailure
{{- end }}

