{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-crm.fullname" . }}-init
  labels:
    {{- include "helm-crm.labels" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }} 
      containers:
      - name: init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "npm run prisma:migrate && npm run prisma:seed"]
        envFrom:
          - secretRef:
              name: {{ include "helm-crm.fullname" . }}
          - configMapRef:
              name: {{ include "helm-crm.fullname" . }}
      restartPolicy: OnFailure
{{- end }}

