{{- if .Values.wwebjs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  name: {{ include "helm-crm.fullname" . }}-wwebjs-auth
  labels:
    {{- include "helm-crm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.wwebjs.storage }}
{{- end }} 