{{- if .Values.wwebjs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-crm.fullname" . }}-wwebjs-auth
  labels:
    {{- include "helm-crm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.wwebjs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wwebjs.storage }}
{{- end }} 